name: mini_chat
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  google_sign_in: ^6.1.5
  keyboard_dismisser:
  image_picker: ^1.0.4
  #firebase
  firebase_core: ^2.14.0
  firebase_auth: ^4.7.0
  cloud_firestore: ^4.9.1
  firebase_storage: ^11.2.6


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg