name: mini_chat
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_sign_in: ^6.1.5
  keyboard_dismisser:
  image_picker: ^1.0.4
  emoji_picker_flutter:
  flutter_notification_channel:
  gallery_saver: ^2.3.2
  flutter_easyloading: ^3.0.5
  easy_localization: ^3.0.3
  http: ^0.13.3
  hive: ^2.2.3
  get_it: ^7.6.4
  go_router: ^11.0.0
  cached_network_image: ^3.2.3
  path_provider: ^2.1.1
  flutter_bloc: ^8.1.3
  freezed: ^2.4.2
  freezed_annotation: ^2.4.1
  #firebase
  firebase_core: ^2.14.0
  firebase_auth: ^4.7.0
  cloud_firestore: ^4.9.1
  firebase_storage: ^11.2.6
  firebase_messaging: ^14.6.8
  firebase_database: ^10.2.5




dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.6
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - images/
    - assets/